name: Rust CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code_check:
    name: Check Code Quality
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: cargo check
        run: cargo check --all --all-features

      - name: cargo format check
        run: cargo fmt --all --check

      - name: cargo test
        run: cargo test --all --all-features

      - name: cargo clippy check
        run: cargo clippy --all --all-features

  doc:
    name: Test Documentation Generation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    needs: ["code_check"]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs