name: Rust CI
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/*'
      - 'src/*'
      - 'Cargo.toml'
  push:
    branches: [ main ]
    paths:
      - 'examples/*'
      - 'src/*'
      - 'Cargo.toml'

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code_check:
    name: Check Code Quality
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: cargo check
        run: cargo check --all --all-features

      - name: cargo format check
        run: cargo fmt --all --check

      - name: cargo test
        run: cargo test --all --all-features

      - name: cargo clippy check
        run: cargo clippy --all --all-features

  publish_documentation:
    name: Publish Documentation to Github IO
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Build Documentaiton
        run: cargo doc --all --no-deps

      - name: Make index.html a link to help.html
        run: cd target/doc && ln -s help.html index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc

      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v1